# -*- coding: utf-8 -*-
"""picking a random card .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-_ZYr65gk8otIo0hYB3QraibyL3TA2DR
"""

import random

cards = ["Diamonds", "Spades", "Hearts", "Clubs"]
ranks = [2, 3, 4, 5, 6, 7, 8, 9, 10, "Jack", "Queen", "King", "Ace"]

def pick_a_card():
    card = random.choice(cards)
    rank = random.choice(ranks)
    return f"The {rank} of {card}"

print(pick_a_card())